name       : texinfo
version    : '6.7'
release    : 10
source     :
    - https://ftp.gnu.org/gnu/texinfo/texinfo-6.7.tar.xz : 988403c1542d15ad044600b909997ba3079b10e03224c61188117f3676b02caa
homepage   : http://www.gnu.org/software/texinfo
license    :
    - GPL-3.0-or-later
component  : system.devel
summary    : texinfo (Documentation format used by GNU)
description: |
    textinfo is the documentation format used by the GNU project, invented by Richard Stallman and Bob Chassell. It is used to take a single source file and produce various outputs such as dvi, html, and pdf.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
