name       : texinfo
version    : '6.3'
release    : 8
source     :
    - https://ftp.gnu.org/gnu/texinfo/texinfo-6.3.tar.xz : 246cf3ffa54985118ec2eea2b8d0c71b92114efe6282c2ae90d65029db4cf93a
homepage   : http://www.gnu.org/software/texinfo
license    :
    - GPL-3.0
summary    : texinfo (Documentation format used by GNU)
component  : system.devel
description: |
    textinfo is the documentation format used by the GNU project, invented by Richard Stallman and Bob Chassell. It is used to take a single source file and produce various outputs such as dvi, html, and pdf.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
